/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "stancl.tenancy.asset": [
        {
            "name": "path"
        }
    ],
    "index": [],
    "destino_economicos.index": [],
    "destino_economicos.create": [],
    "destino_economicos.store": [],
    "destino_economicos.show": [
        {
            "name": "destino_economico"
        }
    ],
    "destino_economicos.edit": [
        {
            "name": "destino_economico"
        }
    ],
    "destino_economicos.update": [
        {
            "name": "destino_economico"
        }
    ],
    "destino_economicos.destroy": [
        {
            "name": "destino_economico"
        }
    ],
    "codigo_destino_economicos.index": [],
    "codigo_destino_economicos.create": [],
    "codigo_destino_economicos.store": [],
    "codigo_destino_economicos.show": [
        {
            "name": "codigo_destino_economico"
        }
    ],
    "codigo_destino_economicos.edit": [
        {
            "name": "codigo_destino_economico"
        }
    ],
    "codigo_destino_economicos.update": [
        {
            "name": "codigo_destino_economico"
        }
    ],
    "codigo_destino_economicos.destroy": [
        {
            "name": "codigo_destino_economico"
        }
    ],
    "rango_avaluos.index": [],
    "rango_avaluos.create": [],
    "rango_avaluos.store": [],
    "rango_avaluos.show": [
        {
            "name": "rango_avaluo"
        }
    ],
    "rango_avaluos.edit": [
        {
            "name": "rango_avaluo"
        }
    ],
    "rango_avaluos.update": [
        {
            "name": "rango_avaluo"
        }
    ],
    "rango_avaluos.destroy": [
        {
            "name": "rango_avaluo"
        }
    ],
    "api.predios.search": [],
    "predios.index": [],
    "predios.store": [],
    "predios.show": [
        {
            "name": "predio",
            "binding": "id"
        }
    ],
    "predios.update": [
        {
            "name": "predio",
            "binding": "id"
        }
    ],
    "predios.destroy": [
        {
            "name": "predio",
            "binding": "id"
        }
    ],
    "api.predios.historial_predios.latest": [
        {
            "name": "predio",
            "binding": "id"
        }
    ],
    "predios.historial_predios.index": [
        {
            "name": "predio",
            "binding": "id"
        }
    ],
    "predios.historial_predios.store": [
        {
            "name": "predio"
        }
    ],
    "predios.historial_predios.show": [
        {
            "name": "predio",
            "binding": "id"
        },
        {
            "name": "historial_predio",
            "binding": "id"
        }
    ],
    "predios.historial_predios.update": [
        {
            "name": "predio"
        },
        {
            "name": "historial_predio"
        }
    ],
    "predios.historial_predios.destroy": [
        {
            "name": "predio"
        },
        {
            "name": "historial_predio"
        }
    ],
    "api.predios.avaluos.latest": [
        {
            "name": "predio"
        }
    ],
    "predios.avaluos.index": [
        {
            "name": "predio"
        }
    ],
    "predios.avaluos.store": [
        {
            "name": "predio"
        }
    ],
    "predios.avaluos.show": [
        {
            "name": "predio"
        },
        {
            "name": "avaluo",
            "binding": "id"
        }
    ],
    "predios.avaluos.update": [
        {
            "name": "predio"
        },
        {
            "name": "avaluo",
            "binding": "id"
        }
    ],
    "predios.avaluos.destroy": [
        {
            "name": "predio"
        },
        {
            "name": "avaluo",
            "binding": "id"
        }
    ],
    "api.igac": []
}
}
export {};
