/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "stancl.tenancy.asset": [
        {
            "name": "path"
        }
    ],
    "index": [],
    "upload_igac.index": [],
    "upload_igac.create": [],
    "upload_igac.store": [],
    "upload_igac.show": [
        {
            "name": "upload_igac"
        }
    ],
    "upload_igac.edit": [
        {
            "name": "upload_igac"
        }
    ],
    "upload_igac.update": [
        {
            "name": "upload_igac"
        }
    ],
    "upload_igac.destroy": [
        {
            "name": "upload_igac"
        }
    ],
    "codigo_destino_economicos.index": [],
    "codigo_destino_economicos.create": [],
    "codigo_destino_economicos.store": [],
    "codigo_destino_economicos.show": [
        {
            "name": "codigo_destino_economico"
        }
    ],
    "codigo_destino_economicos.edit": [
        {
            "name": "codigo_destino_economico"
        }
    ],
    "codigo_destino_economicos.update": [
        {
            "name": "codigo_destino_economico"
        }
    ],
    "codigo_destino_economicos.destroy": [
        {
            "name": "codigo_destino_economico"
        }
    ],
    "destino_economicos.index": [],
    "destino_economicos.create": [],
    "destino_economicos.store": [],
    "destino_economicos.show": [
        {
            "name": "destino_economico"
        }
    ],
    "destino_economicos.edit": [
        {
            "name": "destino_economico"
        }
    ],
    "destino_economicos.update": [
        {
            "name": "destino_economico"
        }
    ],
    "destino_economicos.destroy": [
        {
            "name": "destino_economico"
        }
    ],
    "rango_avaluos.index": [],
    "rango_avaluos.create": [],
    "rango_avaluos.store": [],
    "rango_avaluos.show": [
        {
            "name": "rango_avaluo",
            "binding": "id"
        }
    ],
    "rango_avaluos.edit": [
        {
            "name": "rango_avaluo",
            "binding": "id"
        }
    ],
    "rango_avaluos.update": [
        {
            "name": "rango_avaluo",
            "binding": "id"
        }
    ],
    "rango_avaluos.destroy": [
        {
            "name": "rango_avaluo"
        }
    ],
    "unidad_monetarias.index": [],
    "unidad_monetarias.create": [],
    "unidad_monetarias.store": [],
    "unidad_monetarias.show": [
        {
            "name": "unidad_monetaria"
        }
    ],
    "unidad_monetarias.edit": [
        {
            "name": "unidad_monetaria"
        }
    ],
    "unidad_monetarias.update": [
        {
            "name": "unidad_monetaria"
        }
    ],
    "unidad_monetarias.destroy": [
        {
            "name": "unidad_monetaria"
        }
    ]
}
}
export {};
